//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/Input/InputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @InputActions : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @InputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""InputActions"",
    ""maps"": [
        {
            ""name"": ""Gameplay"",
            ""id"": ""7b4da6a0-f1d0-43da-af20-35098834bfe6"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""165914f2-bdc3-4760-bc21-6069f2d20254"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""2b19a0b0-6d01-480b-be56-8c4d47b401ac"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Attack"",
                    ""type"": ""Button"",
                    ""id"": ""8717038f-70ce-4f98-b1b5-1e8550d8b4a9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Map"",
                    ""type"": ""Button"",
                    ""id"": ""a527995e-d89f-4039-86d4-96f0ac51f590"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Dash"",
                    ""type"": ""Button"",
                    ""id"": ""efdee45e-a6ab-4507-a5e5-0722691c543a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Magic"",
                    ""type"": ""Button"",
                    ""id"": ""cbd74634-d57d-4922-81f5-40356aebfdaa"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Pause"",
                    ""type"": ""Button"",
                    ""id"": ""62afcd88-d2ea-460e-aa37-a2f39562c0c4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""BtnScaleUp"",
                    ""type"": ""Button"",
                    ""id"": ""2eb65144-5d77-425f-b6e5-74c9ad97c0ad"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""BtnScaleDown"",
                    ""type"": ""Button"",
                    ""id"": ""f3f431eb-fbbc-428e-85c3-33812cf24bf4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""BtnXUp"",
                    ""type"": ""Button"",
                    ""id"": ""b44cf8b5-791c-4595-a7ba-959a76f11cad"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""BtnXDown"",
                    ""type"": ""Button"",
                    ""id"": ""a3b5757b-4fdb-4381-bbd9-87b8870a961b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""BtnYUp"",
                    ""type"": ""Button"",
                    ""id"": ""69967b3f-a145-4385-b16c-fb76a53acca9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""BtnYDown"",
                    ""type"": ""Button"",
                    ""id"": ""017577ec-88c5-41e2-b2b3-d77bf4374d2a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""WASD"",
                    ""id"": ""f9b5c981-e1f1-49e2-a5a3-0a1c32d01499"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""bc358f7b-fcc3-4896-8407-78ac272c8cda"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""up"",
                    ""id"": ""e4b838db-f214-4b09-92e3-b3111993b859"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""b99ad6ab-3b4e-47ba-a8a5-efcdfb78ec02"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""0ffb726b-900b-48dd-a8dd-6d9dc99bd1ab"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""21b2052b-cbf0-4f0d-a68d-fed6a3e70e16"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""82560741-f34e-4ff7-88ff-dc5c1e21ac04"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""9378b383-3ab4-43e9-bb75-9d66e5813f86"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""fc640409-e645-4155-a189-78386d61c8c9"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Gamepad"",
                    ""id"": ""3f06620f-df26-4d3f-955e-d6840fdb624e"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""6793d4f2-a53c-4c35-85e6-304aee020d51"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""up"",
                    ""id"": ""eaeabe00-db59-4248-8d46-76560b0aa7b7"",
                    ""path"": ""<Gamepad>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""3d3b1abd-ad3d-4241-9308-62ef44cd726f"",
                    ""path"": ""<Gamepad>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""4325a231-744d-4e05-80cb-9397eb7c949e"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""60a676fe-01aa-42d8-ab13-eeb27ac1022b"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""755c9abd-f4bd-4f16-a2b5-a784951a7736"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""27e593ab-b4c8-4c93-bb01-07963bdf0ff7"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""3e282519-070b-40c9-963b-79b203e5ff38"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""b9e91862-57e2-4977-9045-1f4c08c933f2"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""546bcb72-40a2-41a4-ba2c-ad9fd493f298"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4bbb7e4a-91ee-4a6a-8700-2d4334d0821e"",
                    ""path"": ""<Keyboard>/j"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Attack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""06907edc-ab0b-4dc3-87e8-bcba93c504aa"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Attack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""429c5054-c607-41cb-ad7a-a1a3e2253741"",
                    ""path"": ""<Keyboard>/m"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Map"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""15a16e53-34d8-4fa9-ac51-15d7245be997"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Map"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4ac3be8c-91f8-4091-a564-415fa85c698b"",
                    ""path"": ""<Keyboard>/k"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Dash"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6d9b9656-50c9-490a-99b8-d334afdb408a"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Dash"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4a378e0c-7aae-4de9-b9eb-fea190d126b1"",
                    ""path"": ""<Keyboard>/l"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Magic"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""645b3e93-e6f1-49b4-8171-6c524f737c3a"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Magic"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""56f1f663-3b78-4d28-b08a-a82f32d81dd1"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0547c7d4-ee20-4067-8996-c0220f9f2311"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6dc296ad-2898-4f8a-b998-68f6a48fe9a7"",
                    ""path"": ""<DualShockGamepad>/touchpadButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d486e510-7b4b-4f68-87ef-4575ffa68860"",
                    ""path"": ""<Keyboard>/numpadPlus"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""BtnScaleUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""96f3ea1c-105d-41a6-83c6-1dabf9ca8e2e"",
                    ""path"": ""<Keyboard>/numpadMinus"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""BtnScaleDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""33d0076d-f299-47f4-b39f-e00bbf426d62"",
                    ""path"": ""<Keyboard>/numpadMultiply"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""BtnXUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ffb84cc6-8040-4668-8ae7-3d13bb1731d4"",
                    ""path"": ""<Keyboard>/numpadDivide"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""BtnXDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fdc55b3e-8f12-438d-99ff-2f89837dfd7d"",
                    ""path"": ""<Keyboard>/numpadPeriod"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""BtnYUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b7740ef1-b052-4e06-b8f5-ca90406f36af"",
                    ""path"": ""<Keyboard>/numpadEquals"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""BtnYDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Gameplay
        m_Gameplay = asset.FindActionMap("Gameplay", throwIfNotFound: true);
        m_Gameplay_Move = m_Gameplay.FindAction("Move", throwIfNotFound: true);
        m_Gameplay_Jump = m_Gameplay.FindAction("Jump", throwIfNotFound: true);
        m_Gameplay_Attack = m_Gameplay.FindAction("Attack", throwIfNotFound: true);
        m_Gameplay_Map = m_Gameplay.FindAction("Map", throwIfNotFound: true);
        m_Gameplay_Dash = m_Gameplay.FindAction("Dash", throwIfNotFound: true);
        m_Gameplay_Magic = m_Gameplay.FindAction("Magic", throwIfNotFound: true);
        m_Gameplay_Pause = m_Gameplay.FindAction("Pause", throwIfNotFound: true);
        m_Gameplay_BtnScaleUp = m_Gameplay.FindAction("BtnScaleUp", throwIfNotFound: true);
        m_Gameplay_BtnScaleDown = m_Gameplay.FindAction("BtnScaleDown", throwIfNotFound: true);
        m_Gameplay_BtnXUp = m_Gameplay.FindAction("BtnXUp", throwIfNotFound: true);
        m_Gameplay_BtnXDown = m_Gameplay.FindAction("BtnXDown", throwIfNotFound: true);
        m_Gameplay_BtnYUp = m_Gameplay.FindAction("BtnYUp", throwIfNotFound: true);
        m_Gameplay_BtnYDown = m_Gameplay.FindAction("BtnYDown", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Gameplay
    private readonly InputActionMap m_Gameplay;
    private IGameplayActions m_GameplayActionsCallbackInterface;
    private readonly InputAction m_Gameplay_Move;
    private readonly InputAction m_Gameplay_Jump;
    private readonly InputAction m_Gameplay_Attack;
    private readonly InputAction m_Gameplay_Map;
    private readonly InputAction m_Gameplay_Dash;
    private readonly InputAction m_Gameplay_Magic;
    private readonly InputAction m_Gameplay_Pause;
    private readonly InputAction m_Gameplay_BtnScaleUp;
    private readonly InputAction m_Gameplay_BtnScaleDown;
    private readonly InputAction m_Gameplay_BtnXUp;
    private readonly InputAction m_Gameplay_BtnXDown;
    private readonly InputAction m_Gameplay_BtnYUp;
    private readonly InputAction m_Gameplay_BtnYDown;
    public struct GameplayActions
    {
        private @InputActions m_Wrapper;
        public GameplayActions(@InputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_Gameplay_Move;
        public InputAction @Jump => m_Wrapper.m_Gameplay_Jump;
        public InputAction @Attack => m_Wrapper.m_Gameplay_Attack;
        public InputAction @Map => m_Wrapper.m_Gameplay_Map;
        public InputAction @Dash => m_Wrapper.m_Gameplay_Dash;
        public InputAction @Magic => m_Wrapper.m_Gameplay_Magic;
        public InputAction @Pause => m_Wrapper.m_Gameplay_Pause;
        public InputAction @BtnScaleUp => m_Wrapper.m_Gameplay_BtnScaleUp;
        public InputAction @BtnScaleDown => m_Wrapper.m_Gameplay_BtnScaleDown;
        public InputAction @BtnXUp => m_Wrapper.m_Gameplay_BtnXUp;
        public InputAction @BtnXDown => m_Wrapper.m_Gameplay_BtnXDown;
        public InputAction @BtnYUp => m_Wrapper.m_Gameplay_BtnYUp;
        public InputAction @BtnYDown => m_Wrapper.m_Gameplay_BtnYDown;
        public InputActionMap Get() { return m_Wrapper.m_Gameplay; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(GameplayActions set) { return set.Get(); }
        public void SetCallbacks(IGameplayActions instance)
        {
            if (m_Wrapper.m_GameplayActionsCallbackInterface != null)
            {
                @Move.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnMove;
                @Move.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnMove;
                @Move.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnMove;
                @Jump.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnJump;
                @Jump.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnJump;
                @Jump.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnJump;
                @Attack.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnAttack;
                @Attack.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnAttack;
                @Attack.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnAttack;
                @Map.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnMap;
                @Map.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnMap;
                @Map.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnMap;
                @Dash.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnDash;
                @Dash.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnDash;
                @Dash.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnDash;
                @Magic.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnMagic;
                @Magic.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnMagic;
                @Magic.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnMagic;
                @Pause.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnPause;
                @Pause.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnPause;
                @Pause.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnPause;
                @BtnScaleUp.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnBtnScaleUp;
                @BtnScaleUp.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnBtnScaleUp;
                @BtnScaleUp.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnBtnScaleUp;
                @BtnScaleDown.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnBtnScaleDown;
                @BtnScaleDown.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnBtnScaleDown;
                @BtnScaleDown.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnBtnScaleDown;
                @BtnXUp.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnBtnXUp;
                @BtnXUp.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnBtnXUp;
                @BtnXUp.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnBtnXUp;
                @BtnXDown.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnBtnXDown;
                @BtnXDown.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnBtnXDown;
                @BtnXDown.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnBtnXDown;
                @BtnYUp.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnBtnYUp;
                @BtnYUp.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnBtnYUp;
                @BtnYUp.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnBtnYUp;
                @BtnYDown.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnBtnYDown;
                @BtnYDown.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnBtnYDown;
                @BtnYDown.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnBtnYDown;
            }
            m_Wrapper.m_GameplayActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Move.started += instance.OnMove;
                @Move.performed += instance.OnMove;
                @Move.canceled += instance.OnMove;
                @Jump.started += instance.OnJump;
                @Jump.performed += instance.OnJump;
                @Jump.canceled += instance.OnJump;
                @Attack.started += instance.OnAttack;
                @Attack.performed += instance.OnAttack;
                @Attack.canceled += instance.OnAttack;
                @Map.started += instance.OnMap;
                @Map.performed += instance.OnMap;
                @Map.canceled += instance.OnMap;
                @Dash.started += instance.OnDash;
                @Dash.performed += instance.OnDash;
                @Dash.canceled += instance.OnDash;
                @Magic.started += instance.OnMagic;
                @Magic.performed += instance.OnMagic;
                @Magic.canceled += instance.OnMagic;
                @Pause.started += instance.OnPause;
                @Pause.performed += instance.OnPause;
                @Pause.canceled += instance.OnPause;
                @BtnScaleUp.started += instance.OnBtnScaleUp;
                @BtnScaleUp.performed += instance.OnBtnScaleUp;
                @BtnScaleUp.canceled += instance.OnBtnScaleUp;
                @BtnScaleDown.started += instance.OnBtnScaleDown;
                @BtnScaleDown.performed += instance.OnBtnScaleDown;
                @BtnScaleDown.canceled += instance.OnBtnScaleDown;
                @BtnXUp.started += instance.OnBtnXUp;
                @BtnXUp.performed += instance.OnBtnXUp;
                @BtnXUp.canceled += instance.OnBtnXUp;
                @BtnXDown.started += instance.OnBtnXDown;
                @BtnXDown.performed += instance.OnBtnXDown;
                @BtnXDown.canceled += instance.OnBtnXDown;
                @BtnYUp.started += instance.OnBtnYUp;
                @BtnYUp.performed += instance.OnBtnYUp;
                @BtnYUp.canceled += instance.OnBtnYUp;
                @BtnYDown.started += instance.OnBtnYDown;
                @BtnYDown.performed += instance.OnBtnYDown;
                @BtnYDown.canceled += instance.OnBtnYDown;
            }
        }
    }
    public GameplayActions @Gameplay => new GameplayActions(this);
    public interface IGameplayActions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnJump(InputAction.CallbackContext context);
        void OnAttack(InputAction.CallbackContext context);
        void OnMap(InputAction.CallbackContext context);
        void OnDash(InputAction.CallbackContext context);
        void OnMagic(InputAction.CallbackContext context);
        void OnPause(InputAction.CallbackContext context);
        void OnBtnScaleUp(InputAction.CallbackContext context);
        void OnBtnScaleDown(InputAction.CallbackContext context);
        void OnBtnXUp(InputAction.CallbackContext context);
        void OnBtnXDown(InputAction.CallbackContext context);
        void OnBtnYUp(InputAction.CallbackContext context);
        void OnBtnYDown(InputAction.CallbackContext context);
    }
}
